### ISSUE TITLE
install-static failed

### ISSUE THREAD

**Issue by lecheel** [rgburke/grv#10]
ubuntu 16.04
brand new install 
#go get -d github.com/rgburke/grv/cmd/grv
#cd $GOPATH/src/github.com/rgburke/grv
#make
```
Makefile:14: recipe for target 'install-static' failed
make[1]: *** [install-static] Error 2
make[1]: Leaving directory '/home/lecheel/go_work/src/gopkg.in/libgit2/git2go.v25'
Makefile:34: recipe for target 'build-libgit2' failed
make: *** [build-libgit2] Error 2
```
![sift00](https://user-images.githubusercontent.com/148137/34352318-d08ed702-ea5c-11e7-9d23-214860c1f7d6.PNG)

**Comment by rgburke** [comment]
Thanks for reporting this issue. I was able to reproduce it in an Ubuntu 16.04 container by specifying
```
export CC="ccache gcc"
```
So it seems that using ccache causes it to fail. Do you have the same value for `CC`, or have you enabled ccache in another way?

I was able to work around this by doing:
```
CC=gcc make install
```
Then I was able to build GRV successfully. Could you try the same to see if it works for you? Or could you try building GRV with ccache disabled another way?

**Comment by lecheel** [comment]
yes exactly I've specifying CC="ccache gcc", Thanks the great grv
by the way I try to use standalone but no lucky working with go files which show
"FATAL: Unable to initialise grv: Unable to find a git repository in . or any of its parent directories"

**Comment by rgburke** [comment]
GRV has to be run from inside a repository. So for example:
```
$ git clone https://github.com/rgburke/grv.git
$ cd grv
$ grv
```
GRV should then start up correctly.
Another option is to use the `-repoFilePath` option:
```
$ grv -repoFilePath /path/to/repository
```

**Comment by lecheel** [comment]
thanks it works
