### ISSUE TITLE
can't run it and get a error

### ISSUE THREAD

**Issue by wxlg1117** [rgburke/grv#12]
[root@demotest ~]# uname -a
Linux demotest 2.6.32-696.18.7.el6.x86_64 #1 SMP Thu Jan 4 17:31:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
[root@demotest ~]# ./grv -repoFilePath /data/gitclone/
FATAL: kernel too old
Aborted

which system kernel version is available for ?

**Comment by rgburke** [comment]
Thanks for reporting this issue. The binary attached to the release only supports kernels 3.2.0 and newer. I've recompiled GRV in an Ubuntu 14.04 container and the resulting binary should now support kernels 2.6.24 and newer.

Could you try the steps below and see if it works? (note the new URL):
```
wget -O grv https://github.com/rgburke/grv/releases/download/v0.1.0/grv_v0.1.0_linux64_kernel_2.6.24_support
chmod +x ./grv
./grv -repoFilePath /data/gitclone/
```

**Comment by wxlg1117** [comment]
now it's can running in kernel 2.6.32,thanks very much.

**Comment by rgburke** [comment]
Great, thanks for trying it out. I'll ensure a binary that supports kernels 2.6.24 and later is available in future GRV releases.
