### ISSUE TITLE
Install via homebrew

### ISSUE THREAD

**Issue by matalo33** [rgburke/grv#13]
Looks like a useful tool! Do you have any plans to create a brew formula, or has anyone else started looking at this?

**Comment by rgburke** [comment]
Thanks! I would like for there to be a brew formula. I'm not familiar with brew myself, so if you or someone out there is and would like to create a brew formula then please go ahead and let us know here.

If no one does come forward in the next few days then I can give it a go.

**Comment by matalo33** [comment]
Zero familiarity myself too! Would like to give it a go though, I'll try find some time for this

**Comment by kingsloi** [comment]
👍 100% agree, would be really useful to have!

**Comment by CameronBanga** [comment]
+1 on home-brew support

**Comment by alexadusei** [comment]
Agreed with above!

**Comment by rgburke** [comment]
Thanks to everyone who has commented here, I can see there is a lot of demand for having a brew formula. I will have access to a Mac this weekend so I will be able to create and test a formula then.

**Comment by kirang20** [comment]
+1

**Comment by Jahhein** [comment]
I was also crossing fingers for this!

Pull request made was sadly [closed](https://github.com/Homebrew/homebrew-core/pull/23627)

**Comment by rgburke** [comment]
Yes, I will need to update GRV to vedor it's dependencies first. I will submit a fresh PR and hopefully we will then get GRV into homebrew!

**Comment by rgburke** [comment]
Good news! GRV is now available in homebrew and can be installed with:
```
brew install grv
```
Thanks for your patience everyone.

**Comment by kingsloi** [comment]
You're a great human, @rgburke

**Comment by alexadusei** [comment]
Thanks so much, @rgburke, appreciate it!

**Comment by CameronBanga** [comment]
Already downloaded and playing around, very nice!

**Comment by borNfreee** [comment]
It's awesome. I like tig a lot, but know I also like grv. This is just awesome
