### ISSUE TITLE
Invalid variable tabwidth 

### ISSUE THREAD

**Issue by srvg** [rgburke/grv#17]
According to [documentation.md](https://github.com/rgburke/grv/blob/master/doc/documentation.md)
```
 Variable | Type   | Description
 ---------+--------+----------------------------------------------
 tabwidth | int    | Tab character screen width (minimum value: 1)
```
but setting this
```
❯ cat .config/grv/grvrc 
set tabwidth 4
```
Launching grv yields this error:
```
/home/serge/.config/grv/grvrc:1:5 Invalid variable tabwidth
```

**Comment by rgburke** [comment]
Thanks again for reporting this. I think a search and replace in the past went wrong and left the tabwidth variable with the wrong name 😄. This issue is now resolved in master.
