### ISSUE TITLE
Can we get mouse support?

### ISSUE THREAD

**Issue by heeen** [rgburke/grv#18]
suggesting mouse support to select branches, commites and mouse wheel for scrolling in all views

**Comment by rgburke** [comment]
Yes, mouse support is definitely planned.

**Comment by rgburke** [comment]
GRV now has mouse support. It's possible to select rows in all views and scroll. Click twice on a branch or tag to load the commits for it. Mouse support is disabled by default but can be enabled with the following config:
```
set mouse true
```
To make this persistent modify your `grvrc` with the following command:
```
echo set mouse true >> ~/.config/grv/grvrc
```

**Note**: Scrolling requires that ncurses has been compiled with extended mouse support (apart from on Mac where this isn't necessary). That is, the ncurses configure script has been passed the `--enable-ext-mouse` option.

**Comment by mickdekkers** [comment]
@rgburke thanks for implementing this 🙂 

The version on homebrew (`v0.1.2-0-gffbd489`) doesn't seem to have this feature yet; I followed [the documentation](https://github.com/rgburke/grv/blob/master/doc/documentation.md#set) but I'm getting the error `Invalid variable mouse`.

**Comment by rgburke** [comment]
@mickdekkers grv in homebrew has now been updated to a version with mouse support.

**Comment by rgburke** [comment]
Closing this as mouse support has been added. Please raise any bugs or suggestions as new issues.
