### ISSUE TITLE
Can we get graph view?

### ISSUE THREAD

**Issue by heeen** [rgburke/grv#19]
suggesting a support for something that looks like the output of

git log --color --graph --decorate --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --all

**Comment by rgburke** [comment]
Yes, this is definitely something I want to add. The plan is to use line graphics similar to how tig has done graph support. But I'm open to any suggestions for how it could be done.

**Comment by ryansch** [comment]
I think the tig approach is perfect.

**Comment by rgburke** [comment]
GRV on master has commit graph functionality. It is disabled by default but can be enabled by setting:
```
set commit-graph true
```
in `~/.config/grv/grvrc`.

The graph layout should be mostly equivalent to tig configured with `set commit-order = default`. However there are slight implementation differences which causes the positioning of some branches to be different. This generally manifests itself on projects with complex commit graphs. Both representations should be equivalent.

An example of how the commit graph looks is given below:
![grv-commit-graph](https://user-images.githubusercontent.com/7596018/39020109-9f8ca4ba-4423-11e8-8894-0b7470e157f4.PNG)

Let me know if you have any feedback or suggestions. This was a bit of a pain to implement so there may be some glitches to iron out 😄

**Comment by marcelpaulo** [comment]
I'm using `set commit-graph true` and it's working beautifully !

**Comment by rgburke** [comment]
Closing this issue as the commit graph is implement. Please raise any bugs/suggestions as new issues.
