### ISSUE TITLE
"make install" doesn't work with multiple entries in GOPATH

### ISSUE THREAD

**Issue by Carpetsmoker** [rgburke/grv#2]
```

$ pwd
/home/martin/go/src/github.com/rgburke/grv

$ echo $GOPATH
/home/martin/go:/home/martin/work

$ make install
go get -d ./...
cd /home/martin/go:/home/martin/work/src/gopkg.in/libgit2/git2go.v25 && git submodule update --init;
/bin/sh: line 0: cd: /home/martin/go:/home/martin/work/src/gopkg.in/libgit2/git2go.v25: No such file or directory
make: *** [Makefile:29: build-libgit2] Error 1
```

In general you should never use `$GOPATH` directly since it works like `$PATH`: it can have multiple entries.

It's probably better to get the path relative to the running Makefile; e.g. `readlink -f $0` from a shell script (I'm not sure how to do that in a Makefile though, it's been over ten years since I last used make in any serious capacity).

**Comment by rgburke** [comment]
Thanks for pointing out the misuse of `$GOPATH`, this should be resolved by 0544c19.
