### ISSUE TITLE
grv won't show commit message

### ISSUE THREAD

**Issue by FredrikSvep** [rgburke/grv#20]
When viewing a commit, the commit message is not shown, only the first line of the commit message.

This leaves out important information.

**Comment by rgburke** [comment]
Yes, the commit view only shows the first line of a commit message. The full commit message is visible in the diff view for the selected commit.

The commit view is designed around having a single line per commit. So if we did want the full commit text then it would need to be joined onto a single line. Is this along the lines of what you were thinking?

**Comment by iveqy** [comment]
I'm fine with only the first line shown in the commit view. That's the way it should be. However in the diff view, the whole commit message should be shown. See the screenshots between of tig and grv here:

![giv](https://user-images.githubusercontent.com/761743/35705256-35ff69c8-07a2-11e8-8684-2e898c3eb9e3.png)
![tig](https://user-images.githubusercontent.com/761743/35705257-361ea75c-07a2-11e8-88f6-4e9820f384df.png)

Do I miss something? It doesn't work as I understand from you that it should work

**Comment by rgburke** [comment]
Thanks for the screenshot, that makes it a lot clearer. You haven't missed a thing, this is bug with GRV. The whole commit message should be visible in the diff view. I will look into this.

**Comment by iveqy** [comment]
Thanks you for your quick reply. I'm looking forward to test a new version

**Comment by rgburke** [comment]
This should now be resolved on master. I've given this a quick test and the full commit message is now showing. Could you confirm using the latest master version of GRV that the full commit message is also showing for you?

**Comment by iveqy** [comment]
Works fine, thanks!

**Comment by rgburke** [comment]
Great, thanks for testing it out.
