### ISSUE TITLE
Terminal color theme is overriden by default

### ISSUE THREAD

**Issue by lbatalha** [rgburke/grv#22]
grv overrides the theme being used by the terminal. Ideally it should not or there should be a quick way to not enforce this.

This would be in line with other ncurses based applications.

**Comment by rgburke** [comment]
Thanks for raising this. GRV's default theme is `solarized` which uses hardcoded colours. There is a `classic` theme which uses standard ncurses colours and should respect the terminal colour palette. If you do
```
:set theme classic
```
in GRV then the `classic` theme will be activated.

Would you be OK with using the `classic` theme?

**Comment by lbatalha** [comment]
Thanks, that seems to completely solve the problem and can be set in grvrc config.
Maybe adding a small note to the docs in the theme section indicating that this is a built in theme, as it does not specify which themes are available out of the box.

**Comment by rgburke** [comment]
That's a good point. I've updated the documentation to list the available themes.
