### ISSUE TITLE
Can't scroll in linux repo

### ISSUE THREAD

**Issue by iveqy** [rgburke/grv#25]
So the linux repo is pretty huge. tig is really slow here, but grv is starting quicker (the second time it's started). Anyway, scrolling in the linux commits makes grv to display some errors:

https://asciinema.org/a/WSYzGvewkcX3BAsZWqmypBjnV

**Comment by rgburke** [comment]
Thanks for reporting this, and for the demo as well. I haven't tried GRV on the linux repo yet but it looks like it would be a good stress test.

**Comment by mckellyln** [comment]
I have a similar issue.  I'm using Ubuntu 16.04.
Scrolling commit or diff window up to top (causing scroll) after scrolling down to bottom (causing scroll) does not display properly - some lines are not redrawn.
Interestingly if I do this slowly, like one line at a time (not holding down arrow buttons) then it seems so far to display correctly.

**Comment by rgburke** [comment]
This should be resolved on master. Please see #39 for more details.
