### ISSUE TITLE
command ":help" does not provide help

### ISSUE THREAD

**Issue by vielmetti** [rgburke/grv#32]
Invalid command "help"  

Good news: built without incident on Mac OS X 10.12.6, after installing dependencies via Homebrew. But I went to the command line trying to figure out how it worked for the first time, and the command "help" didn't work as expected.

**Comment by rgburke** [comment]
Thanks for reporting this. It would be useful to add the ability to view help/documentation from grv itself. There is currently documentation but it's only available online [here](https://github.com/rgburke/grv/blob/master/doc/documentation.md).

**Comment by rgburke** [comment]
A `:help` command has now been added to GRV on master. This command opens a new tab which contains documentation:

![image](https://user-images.githubusercontent.com/7596018/41685168-88719738-74d7-11e8-9022-410791dd32ef.png)

**Comment by vielmetti** [comment]
Thank you for adding this!

**Comment by rgburke** [comment]
Happy to help. Thanks for raising this, the `:help` command was definitely needed.
