### ISSUE TITLE
git2go.v26

### ISSUE THREAD

**Issue by oandrew** [rgburke/grv#33]
The latest `libgit2` on os x via homebrew is 0.26.

Do you think you could switch to git2go.v26?
That would make `grv` installation (at least for Mac users) as easy as 
`go get github.com/rgburke/grv/cmd/grv`

**Comment by oandrew** [comment]
p.s. just noticed the other issue about the libgit2.

in my case I build it with 0.26 and it seems to work ok.
I don't know if there are any breaking changes 0.25->0.26 though. 
thanks!

**Comment by rgburke** [comment]
Yes, I would like to switch to git2go v26, as you point out GRV builds successfully with v26. One small issue that we'll need to work around for v26 is https://github.com/libgit2/git2go/issues/407. We still need to maintain the ability to statically build libgit2 on systems with older versions of libgit2, as git2go will only compile successfully if the exact matching version of libgit2 is available.

However there is no reason why we can't make the move. I will have a look into this.

**Comment by oandrew** [comment]
Also, as a possible temporary fix you could have a separate branch (e.g. git2go-v26) which uses git2go v26  and then the app would be available as 
`go get gopkg.in/rgburke/grv.git2go-v26/cmd/grv`

**Comment by rgburke** [comment]
GRV now uses git2go.v26
