### ISSUE TITLE
Document the instruction how to build on mac

### ISSUE THREAD

**Issue by hypnoglow** [rgburke/grv#4]
Personally, I couldn't build grv on macOS. I have **ncurses** and **readline**, but they seem to be incompatible or smth, because building process fails with issues like this:
```
cmd/grv/readline.go:200:30: could not determine kind of name for C.rl_display_prompt

clang errors for preamble:
cmd/grv/readline.go:14:2: error: use of undeclared identifier 'rl_catch_signals'
        rl_catch_signals = 0;
```

**Comment by rgburke** [comment]
Thanks for pointing this issue out and for trying GRV, I really appreciate it. Some changes have been made to get GRV to build on a Mac, however they're a little bit hacky. 

The readline directory path has been hardcoded as `/usr/local/Cellar/readline/7.0/` at the top of `readline.go`. This works on my Mac and hopefully should on yours, however it assumes you use homebrew and have the Cellar directory in `/usr/local/`. You may potentially need to change this file path to get it to build.

I will look into a way to determine these paths in the Makefile and pass them as build arguments to avoid any manual configuration in future.
On a separate note, the selected lines in GRV don't dim on the Mac (using iTerm2), so I'll investigate why ncurses is behaving differently between Linux and Mac.

**Comment by hypnoglow** [comment]
Thanks, I changed path in `readline.go` and it finally compiled.
Btw, I think the path should be changed for a compatible variant **/usr/local/opt/readline**, as `brew info` states:

```
ή brew info readline
readline: stable 7.0.3 (bottled) [keg-only]
Library for command-line editing
https://tiswww.case.edu/php/chet/readline/rltop.html
/usr/local/Cellar/readline/7.0.3_1 (46 files, 1.5MB)
  Poured from bottle on 2017-05-23 at 16:48:22
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/readline.rb
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only..

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include
```

**Comment by sn0w** [comment]
+1 for `/opt`. Just faced this exact same problem.
Also please add a hint to your readme that people need to install homebrew and readline on OSX.

**Comment by rgburke** [comment]
Thanks for the feedback and help with this guys, #6 has been merged and I've updated the README.

**Comment by raylu** [comment]
sorry if this is the wrong place to report

```
$ go version
go version go1.9.4 darwin/amd64

$ git show
commit ffbd489206c5e76b5c2e7ac251f088880678ea06 (HEAD -> master, tag: v0.1.2, origin/master, origin/HEAD)
Author: Richard Burke <rich.g.burke@gmail.com>
Date:   Wed Feb 7 20:15:05 2018 +0000

$ make
[...]
go build github.com/rgburke/grv/cmd/grv/vendor/gopkg.in/libgit2/git2go.v25: invalid pkg-config package name: --static
make[1]: *** [install-static] Error 1
make: *** [build-libgit2] Error 2

$ go build --tags static -ldflags "-X 'main.version=v0.1.2-0-gffbd489' -X 'main.headOid=ffbd489' -X 'main.buildDateTime=2018-02-07 13:37:56 PST'" -o grv ./cmd/grv
go build github.com/rgburke/grv/cmd/grv/vendor/gopkg.in/libgit2/git2go.v25: invalid pkg-config package name: --static
```

**Comment by rgburke** [comment]
@raylu Thanks for reporting this. Could you create a new issue for this please?

**Comment by raylu** [comment]
done! #38
