### ISSUE TITLE
map usage with filtering

### ISSUE THREAD

**Issue by gabriel-vasile** [rgburke/grv#42]
Hi, I need help with mapping. What I'm trying to do is filter the commits by `comittername`.
My map looks like this:
`map CommitView m <grv-filter-prompt>committername="some_name"<Enter>`
however it does not seem to work: the program freezes when I go into commit view and press `m`.
I also tried
`map CommitView m <C-q>committername="some_name"<Enter>` with the same result.

Is possible to do what I'm trying? Thanks!

**Comment by rgburke** [comment]
Thanks for reporting this.  What you're trying to do is correct, however GRV is not handling the input correctly. I will look into fixing this bug.

**Comment by rgburke** [comment]
This issue is now fixed on master. I tested it using the following mappings:
```
map CommitView m "<grv-filter-prompt>committername=\"Richard Burke\"<Enter>"
map All <C-c> <grv-prompt>q<Enter>
```
Note that the second argument had to be enclosed in quotes as it contained a space.

**Comment by gabriel-vasile** [comment]
Thanks! It works.
