### ISSUE TITLE
NCurses Cursor failed: Failed to enable 

### ISSUE THREAD

**Issue by swill** [rgburke/grv#43]
I have tried installing with `brew install grv` as well as using the MacOS build instructions.  In both cases, everything seems to build and install correctly, but when I try to use the tool I always get the following error.

```
FATAL: Unable to initialise grv: NCurses Cursor failed: Failed to enable 
```

Is this a `PEBKAC` error, or is this a real error that I just need to find the solution or workaround to?

**Comment by rgburke** [comment]
Thanks for reporting this error. On initialisation GRV attempts to hide the terminals cursor and if it fails treats this as a fatal error. However this shouldn't really a fatal error, as GRV can still be used. It's just that the cursor will appear in the bottom right corner of the screen.

I've updated master not to treat the failure to change visibility of the cursor as an error. Could you pull and build the latest master and see if you're now able to run GRV?

Also just out of interest, which terminal emulator are you using? What's the value of your `$TERM` environment variable? I wouldn't normally expect hiding the cursor to fail as other Mac users haven't run into this issue.

**Comment by swill** [comment]
This fixes the error and application loads in my terminal.  I am using the built in MacOS Terminal, nothing special.

``` bash
$ echo $TERM
ansi
```

Here is a screenshot of the `grv` when it loads now.

![grv](https://user-images.githubusercontent.com/13644/36328802-91717252-1331-11e8-8d6f-4b72a2d45f6f.png)

**Comment by swill** [comment]
Just a note, once the app launches, I can not seem to figure out how to actually exit the app.  I have to close the terminal window to exit.  Is that normal or do I just not know the key commands to exit?  I tried `Ctrl + C` and that didn't work.  I tried a few things and was not able to exit.

**Comment by rgburke** [comment]
To exit grv type `:q` and then hit the enter key. This probably seems a bit cryptic but it is the standard way to exit an application with Vi like keybindings.

Having `TERM=ansi` limits the capabilities of the terminal which is why a lot of the line graphics appear as letters like `??` and `qqq...`. If you try running grv as:
```
TERM=xterm-color grv
```
instead of typing `grv` does it look more like [this](https://github.com/rgburke/grv/blob/master/doc/screenshots.md)?

**Comment by swill** [comment]
Sorry for the delay @rgburke, but I just wanted to follow up to let you know that the following made everything work as expected.  Thanks...

```
TERM=xterm-color grv
```

**Comment by swill** [comment]
For others who want to know where this setting is defined on Mac (other than your `.bash_profile` obviously).

`Terminal > Preferences > Profiles > Advanced > Terminfo`

![image](https://user-images.githubusercontent.com/13644/36425932-8108bc9e-1616-11e8-8799-1a59f28ff492.png)
