### ISSUE TITLE
Doesn't support libgit2 > v0.25

### ISSUE THREAD

**Issue by oblitum** [rgburke/grv#5]
I'm on libgit2 0.26, it doesn't build with:

```
~ ❯❯❯ go install github.com/rgburke/grv/cmd/grv
# gopkg.in/libgit2/git2go.v25
.go/src/gopkg.in/libgit2/git2go.v25/git.go:8:3: error: #error "Invalid libgit2 version; this git2go supports libgit2 v0.25"
 # error "Invalid libgit2 version; this git2go supports libgit2 v0.25"
   ^~~~~
```

So the README doesn't follow. I'm using the alternative install mechanism.

**Comment by rgburke** [comment]
Yes, the README was incorrect and I've updated it to clarify that only libgit2 0.25 is supported. In future I would like GRV not to be tied to a specific libgit2 version and for it to be dynamic/configurable. Many thanks for pointing this out!

**Comment by oblitum** [comment]
This project is great, really thank you for it.
