### ISSUE TITLE
Can't map the <Space> key

### ISSUE THREAD

**Issue by marcelpaulo** [rgburke/grv#52]
I'd like to map the space key to `<grv-next-page>` in all views, these are the variations I tried:

```
map All <Space> <grv-next-page>
map All <space> <grv-next-page>
map All <SPACE> <grv-next-page>
```

I tried them both as a `:` command in the TUI, and in the _~/.config/grv/grvrc_ file, but the mapping doesn't take effect. Actually, <Space> can't be mapped to any grv action.

I'm running grv c1bfab3e330a5931a2e7b872b2d03d9777f25fda built from source on Xubuntu 17.10.

**Comment by rgburke** [comment]
Thanks for reporting this. NCurses does not report the space key as a special key but as the ascii space character. The mapping is possible using a space character:
```
map All " " <grv-next-page>
```

**Comment by marcelpaulo** [comment]
Hey, great, thanks, @rgburke, it works ! Great software you developed: once one starts to use it, it's impossible to stop !
