### ISSUE TITLE
Checkout to any commit or branch

### ISSUE THREAD

**Issue by JulioJu** [rgburke/grv#54]
Hi !

Thanks for your work !

It's very cool to have a command line tool to view a git repository ;-) ! But maybe, when we looking for to a commit, a useful thing we want to do is to checkout to any selected commit or branch ? 

I know this feature could diverge from the main goal of grv « ` a terminal interface for viewing git repositories` ». But maybe it could be very cool ! This feature could follow directly the main goal: view… then checkout to branch or commit selected.

What do you think about this idea ?

**Comment by rgburke** [comment]
Thanks for the feedback. The inital goal for grv was to be read-only, however it's become clear that it would be useful to have the ability to modify repository state. I think being able to checkout or branch off from a commit would be a nice feature to have. A couple of others have also suggested functionality I would like to add that modifies the repository in #41.

Once the commit graph is finished, I intend to start work on adding basic functionlity such as branch, delete branch, stage file, unstage file, etc.

**Comment by JulioJu** [comment]
Cool :-) ! Thanks for your work !

**Comment by rgburke** [comment]
GRV on master can now checkout a local branch, remote branch, tag or commit by pressing `c` in the RefView or CommitView.

For a remote branch, if no local branch exists which tracks that remote branch then a new local tracking branch is created and checked out. This is equivalent to the behaviour of `git checkout`.

Let me know if you have any suggestions.

**Comment by JulioJu** [comment]
@rgburke ok so cool :-) ! Thanks :-) ! I've tested, work well… But, I don't know if it's easy to have a confirmation prompt? Because if we type accidentently on key "c", it could be annoying !

**Comment by rgburke** [comment]
Thanks for the suggestions guys. My preference is to checkout a ref by just typing `c` as it's quick and efficient. Having to confirm every checkout could become annoying.

One option is to add a confirmation dialogue box when doing a checkout but make it configurable, so that the confirmation dialogue box can be enabled/disabled. Then users have the option whether they want to confirm every checkout or not.

**Comment by JulioJu** [comment]
@rgburke so cool ;-)
Maybe, the default configuration could be a prompt… For newbies ;-)

**Comment by rgburke** [comment]
GRV on master now prompts the user with a yes/no question to confirm if they want to checkout a branch/commit. This behaviour is enabled by default and can be disabled by adding:
```
set confirm-checkout false
```
to `~/.config/grv/grvrc`.

Let me know if you have any thoughts.

**Comment by rgburke** [comment]
Closing this as it's now possible to checkout any ref or commit with confirmation configurable. Please raise any bugs/suggestions as new issues.
