### ISSUE TITLE
Status bar could dynamically show current key bindings

### ISSUE THREAD

**Issue by marcelpaulo** [rgburke/grv#58]
Following #57, I realized that if one of the key bindings on the status bar is remapped, the status bar still shows the default key bindings. It would be quite useful if the status bar dynamically reflected the current keybindings.

I'm running grv ff99964 on Xubuntu 18.04.

**Comment by rgburke** [comment]
Thanks for spotting this and creating the issue to track it. The latest master version should now correctly relflect the current keybindings.

**Comment by marcelpaulo** [comment]
Hey, @rgburke, I'm to thank you for being always so kind, patient and attentive ! I've just tested the latest master: working great ! Even the shortcut for closing the box with available actions is picking up what I defined for `<grv-remove-view>` (I remapped `<grv-remote-view>` to `d`, and `<grv-exit>` to `q`). Really great !

I saw that you also added the new mappable actions to the documentation, which is really useful !

**Comment by rgburke** [comment]
@marcelpaulo I'm glad to help. I also want to thank you for finding and testing these issues to help make grv better. I really appreciate it.
