### ISSUE TITLE
Alias or cmd prompt for all git commands

### ISSUE THREAD

**Issue by gabeduke** [rgburke/grv#59]
It would be helpful to have either an alias command or to be able to drop to a git prompt and enter any git command manually. While having aliases for specific commands through UI is nice I often just have questions or actions that could be solved w/ git commands. 

For example:
`:git status` > shows a dialog w/ the response ( or `:g status` )
`:git stash` > ( rather than exit grv in order to stash and switch branches )

**Comment by rgburke** [comment]
I really like this idea. GRV won't able to support the full range of actions and flags offered by the git cli commands, so it would be useful to be able to run any git command from within GRV. I will look into adding this functionality.

**Comment by gabeduke** [comment]
Awesome!!  :)

**Comment by mckellyln** [comment]
Yes, this is awesome news.
thx so much for GRV.

**Comment by gabeduke** [comment]
This is exactly what I was requesting! :smile:
