### ISSUE TITLE
<grv-remove-view> has to be run twice to remove Help View

### ISSUE THREAD

**Issue by marcelpaulo** [rgburke/grv#61]
Just noticed now that `<grv-remove-view>` has to be run twice to completely remove the `Help View`. I have `<grv-remove-view>` mapped to `d`: when I pressed it the first time, I all the text is cleared by the view stays on:
![image](https://user-images.githubusercontent.com/10074769/41193148-025490b6-6bdf-11e8-9be1-da1f260bd276.png)

When a press it for the second time, then the view is removed:
![image](https://user-images.githubusercontent.com/10074769/41193157-1225b434-6bdf-11e8-8e18-8442e264cee3.png)

**Comment by rgburke** [comment]
Once again thanks for finding and reporting this issue. It should now be fixed on master.

**Comment by marcelpaulo** [comment]
Just tried it, working flawlessly !
