### ISSUE TITLE
Switch back to the last active view after closing the Help View

### ISSUE THREAD

**Issue by marcelpaulo** [rgburke/grv#62]
This `Help View` is getting better and better with each new commit !

This is something I noticed when you introduced the `Help View`, but I felt I was being too nitpicky to open an issue about it, but as I started to use it more frequently, I realized it was necessary. Allow me a suggestion: when closing the `Help View`, switch back to the last active view. When I start grv with the default views, first `History View` then `Status View` and the `History View` is active. When I open the `Help View`, it's opened after the `Status View`, so when I close it, the `Status View` becomes the active view, and not the `History View` where I was before, so I always have to switch back to the `History View`.

If not switching back to the last active view, perhaps then open the `Help View` right after the current active view, so that when it's closed, the last active view gets focus.

**Comment by rgburke** [comment]
Thanks for raising this, it's been starting to annoy me too 😄 . I definitely agree that grv should switch back to whichever view was previously active when closing a view. At the moment grv doesn't maintain any history of user position, so when a view or tab is closed it will simply switch to the nearest.

One idea to solve this is to introduce tracking of positions analogous to vim's jumplist. Then it will be possible to go back to the correct view on closure. This could also have other nice use cases such as jumping back to a previous position after a search or navigating through previous positions using `<C-o>` and `<C-i>` as is possible in vim.

**Comment by marcelpaulo** [comment]
Wouldn't it be feasible to open new views right after the currently active view, instead of the last view ? This way, you wouldn't have to change the current closing behavior, of switching to the nearest.

Of course, a jumplist would be really nice, but it gives the impression of being harder to implement.

**Comment by rgburke** [comment]
Views should now behave as discussed on master.

**Comment by marcelpaulo** [comment]
Hey, it's working really well, I've just tested it ! It's really good to have all help within grv without having to open the browser. Thanks, @rgburke !
