### ISSUE TITLE
grv name conflicts with oh-my-zsh git plugin alias

### ISSUE THREAD

**Issue by wendigo** [rgburke/grv#7]
Hi,

Just to let you know: grv's name conflicts with https://github.com/robbyrussell/oh-my-zsh git plugin alias: ```grv='git remote -v'```

It took me some time to figure it out why after installing grv it doesn't work ;)

https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L213

**Comment by rgburke** [comment]
Ah, I thought I'd found a three letter permutation that no one had used yet with grv, but it looks like I was wrong 😄.

I'm a bit reluctant to change the name as it's short, convenient to type and the name GRV has been used all over the codebase. It would also be tough to find an alternative name that is short and doesn't conflict with another existing command.

There are potentially a couple of options to try and work around this:
- Make the generated binary name configurable in the Makefile
- During a `make install` detect if the command name grv is already in use and fallback to an alternative binary name, and alert the user this has occurred.

I'm open to any thoughts or suggestions on this? Maybe there's a better way this could be handled?

**Comment by wendigo** [comment]
Yeah, one of the two hardest things in computer science: naming 😆 

I guess that making configurable binary name during make install is some way to address this issue 👍

**Comment by rgburke** [comment]
The binary name generated is now configurable. It can be set by editing the Makefile or by running:
`make install BINARY=NewBinaryName`

The downside of this approach is that other go tools won't necessarily work with the new binary name.
For example, `go clean -i ./cmd/grv` will only remove a binary named grv.

**Comment by hanjianqiao** [comment]
Or... I just comment out [alias grv='git remote -v'](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/git/git.plugin.zsh#L213). Am I right? It works fine so for so good.

**Comment by rgburke** [comment]
Yes, commenting out that line will work. Another option is to add `unalias grv` to the end of your `.zshrc`, then it wouldn't matter if `git.plugin.zsh` was ever updated/overwritten.

**Comment by hanjianqiao** [comment]
Great idea!

**Comment by damienstanton** [comment]
These are reasonable options, however one concern I have is that a _lot_ of developers use oh-my-zsh.

Since we have `make install BINARY=NewBinaryName` perhaps the only change needed is updating the README to indicate that oh-my-zsh users must do this if they want to keep `grv` aliased?

**Comment by rgburke** [comment]
Thanks for the README suggestion, I agree it is better to list the options available there rather than have people stumble onto this issue. I've updated it with the options we've discussed above.

**Comment by rgburke** [comment]
As no one has commented on this in a while and the README has been updated to make it clear there is a conflict with `oh-my-zsh`, I am closing this issue.
