### ISSUE TITLE
How to customize tabs and views with configuration commands

### ISSUE THREAD

**Issue by sibevin** [rgburke/grv#83]
I try to customize tabs and views with configuration commands, but have some problems:

1. We can add a CommitView with the origin/master branch with the command `addview CommitView origin/master` , but how to add a CommitView with the current branch in the repo folder, just like the `git log` default behavior ?

2. Is it possible to remove the default tabs and views ? For example, I use the following commands:
```
addtab Main
addview CommitView origin/master
```
and grv would show the new "Main" tab with a CommitView inside, but the default "History View" and "Status View" are still existing. How to configure grv to show the "Main" tab only ?

3. Is it possible to remove the default views in an existing tab ? For example, the default "History View" tab contains "Refs", "Remotes", "Commits" and "Diff", but I seldom use "Refs" and "Remotes". How to configure grv to show "History View" without these two views by default ?

**Comment by rgburke** [comment]
This functionality is now available in the latest version of GRV (v0.3.1). Placing the example snippet above in a `grvrc` should work.
