### ISSUE TITLE
Cannot stage files when in a subdirectory

### ISSUE THREAD

**Issue by shaform** [rgburke/grv#87]
GRV - Git Repository Viewer v0.3.1-0-g8215c1a (compiled with go1.11.4 at 2019-01-08 22:25:45 GMT)

Say we a have repo,

```
.
└── hh
    └── hh
        ├── a
        └── b
```

If we do
```bash
cd hh/hh
grv
```

Then we could open the `grv` window, but when we try to stage `a` or `b` we get,

> Git command failed: exit status 128

**Comment by rgburke** [comment]
Thanks for reporting this issue. GRV uses file paths relative to the root of the repository and didn't take into account it's working directory. This should now be resolved on master.

**Comment by shaform** [comment]
Thanks! I've tried the master version and it does seem to work.
