### ISSUE TITLE
Cannot leave command prompt without typing anything

### ISSUE THREAD

**Issue by strboul** [rgburke/grv#88]
Not very possible to quit the command mode and return to the application without typing anything. To reproduce this bug, let's think about *a user*:

1) Presses `:` to type a command (where it sees `Enter a command` prompt)
2) Decides not to enter any command and wants to leave
3) Cannot quit command mode because pressing `q` and `Esc` (or even mouse clicks) do not help the user go back to the previous state
4) User types `:q` to quit `grv` completely.

I quite like this command console mode which resembles *vim* to me, and I think it is one of the best things when using *grv*. However, I find myself in tedious situations because of the reason mentioned above.

```
$ grv --version
GRV - Git Repository Viewer v0.3.1-0-g8215c1a (compiled with go1.11.4 at 2019-01-13 00:20:26 GMT)
```

Thanks for the help!

**Comment by rgburke** [comment]
It should be possible to leave the command mode by hitting the Enter key. This method also works in vim as well. Does that solve the issue for you?

**Comment by strboul** [comment]
Yes, hitting the `Enter` key works. It solves my issue but I would be happy if this is implemented as a feature (to be able to quit by `Esc` or `<C-c>` just like in *vim*).

**Comment by rgburke** [comment]
`Esc` or `<C-c>` can now be used to quite the prompt in the latest version of grv (0.3.2)
