### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by cristaloleg** [rgburke/grv#9]
I see this message constantly in a log with log level set to DEBUG
```[FATAL] [main.go:34] - config value 'branch.my.remote' was not found```
App doesn't start at all, any ideas?

**Comment by rgburke** [comment]
Thanks for reporting this issue. The error message `config value 'branch.my.remote' was not found` is generated by libgit2 on initialisation. It looks like libgit2 is failing to parse your git config files.

I've tried modifying my git config to replicate this issue but I haven't been able to. To help track down the issue could you:

- Confirm if you're seeing this error on only one single repository or multiple different repositories.
- Check the `.git/config` of the repository the error occurs with to see if there are any entries relating to `branch.my.remote` e.g. Is there something like:
```
[branch "my"]
        remote = origin
        ...
```

**Comment by cristaloleg** [comment]
Here is my gitconfig:
```
[credential]
        helper = cache --timeout 360000
[user]
        name = <name>
        email = <email>
[alias]
    fap = fetch --all --prune

        pl = pull
        ps = push origin
    st = status
    sq = squash

    co = checkout
    cb = checkout -b
    ci = commit
    df = diff

    put = stash save
    lst = stash list
    set = stash apply
    pop = stash pop

    lg = log --pretty=format:"%h" --graph
    ll = log --pretty=format:"%h" --oneline
    ls = log --oneline --graph --all --decorate=short
    lf = log --follow
[push]
        default = current
```

**Comment by cristaloleg** [comment]
BTW, I've recompiled my libgit2 and now everything works fine, so I'll close this issue ;)
