### ISSUE TITLE
Freeze with 'git push'

### ISSUE THREAD

**Issue by nvuaille** [rgburke/grv#93]
Steps:
 - in RefView
 - press p to push (only one remote, my github repo)
 - the 'command view' displays this:
 ```
Running git push
: Cmd Prompt g...
sername for https://github.com':
```
At this point grv does not respond anymore to any keyboard input, I had to kill it.

Tested with grv v0.3.2-0-g13658da

[Edit]
I see that in this case I should run `:giti push`. Is there a way to bind 'p' to this command when necessary ?

**Comment by rgburke** [comment]
Ideally GRV should handle the case where a password needs to be entered better. You're right that there is a workaround by doing:
```
map RefView p ":giti push origin ${branch}<Enter>"
```

**Comment by nvuaille** [comment]
Thanks for the config line, it does the trick !
